//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteAlbum
    {
        public int IDFavorite { get; set; }
        public string IDacount { get; set; }
        public Nullable<int> iDMusic { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblMusic tblMusic { get; set; }
    }
}
