//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayMusic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblMusic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMusic()
        {
            this.nhactts = new HashSet<nhactt>();
            this.FavoriteAlbums = new HashSet<FavoriteAlbum>();
        }

        public int iDmusic { get; set; }

        public string iDacc { get; set; }

        [Required(ErrorMessage = "Tên bài hát không được để trống.")]
        [Display(Name = "Tên Bài Hát")]
        public string DisplayName { get; set; }

        [Display(Name = "Hình Ảnh")]
        public string Image { get; set; }

        [Display(Name = "Tệp Âm Thanh")]
        public string Data { get; set; }

        [Display(Name = "Lời Bài Hát")]
        public string Cotenttype { get; set; }

        [Display(Name = "Lượt Nghe")]
        public Nullable<int> luotnghe { get; set; }

        [Required(ErrorMessage = "Tên ca sĩ không được để trống.")]
        [Display(Name = "Ca Sĩ")]
        public string casi { get; set; }

        [Display(Name = "Chủ Đề")]
        public Nullable<int> idchude { get; set; }

        public virtual chude chude { get; set; }
        public virtual ICollection<nhactt> nhactts { get; set; }
        public virtual tblAccount tblAccount { get; set; }
        public virtual ICollection<FavoriteAlbum> FavoriteAlbums { get; set; }
    }
}
