//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLog
    {
        public int Id { get; set; }
        public System.DateTime ViewDate { get; set; }
        public int Count { get; set; }
    }
}
